### ISSUE TITLE
Can't install to try it out

### ISSUE THREAD

**Issue by jemmyw** [pgpkg/pgpkg#3]
Running the commands in the tutorial:

```
 → go install github.com/pgpkg/cmd/pgpkg 
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/pgpkg/cmd/pgpkg@latest' to install the latest version
```

```
 → go install github.com/pgpkg/cmd/pgpkg@latest
go: github.com/pgpkg/cmd/pgpkg@latest: module github.com/pgpkg/cmd/pgpkg: git ls-remote -q origin in /Users/jeremyw/src/go/pkg/mod/cache/vcs/e3e5a5b965ea798945972b3225c347729506b1b4f2c03c19924f93515637ac7a: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/pgpkg/cmd/' not found
```

**Comment by doctor-eval** [comment]
Hi Jemmy, I'm so sorry, I did not have notifications set up for issues and missed this. Did you resolve it?

I've been working on pgpkg today, but unfortunately I have run out of time to look into this. If I hear back from you I'll set up a VM and sort it out.

**Comment by doctor-eval** [comment]
Hi again - I'm sorry this failed; I've updated the docs. Basically you need to use:

```
go install github.com/pgpkg/pgpkg/cmd/pgpkg@latest
```

This works for me in a fresh Alpine Linux VM.

I will look at setting up some GH actions soon, so you will be able to just download a binary. Sorry again for the long delay.

**Comment by doctor-eval** [comment]
I've started working on the CI/CD chain, but hopefully the changes to the docs will help. I'm working towards creating a homebrew package to start. I've also fixed my notifications :) I'll close this issue for now but please reach out if you want to give it another shot.
