### ISSUE TITLE
Purge fails with object that must be quoted

### ISSUE THREAD

**Issue by felixyz** [pgpkg/pgpkg#4]
Deploy fails when a trigger on a table that must be quoted is among the managed objects.

```
postgres@localhost:my_db> select * from pgpkg.managed_object
+-----+-----+----------+-------------------------------------------------------+
| pkg | seq | obj_type | obj_name                                              |
|-----+-----+----------+-------------------------------------------------------|
| foo | 0   | function | bar.find_mail_id()                           |
| foo | 1   | trigger  | insert_mail_id_trigger on bar.FOO_Table |
| foo | 2   | function | bar.matching_mail(name text)                 |
+-----+-----+----------+-------------------------------------------------------+
```

```
❯ pgpkg try --verbose
...
pgpkg: 2024/10/11 16:59:14 parsing MOB dbstuff/bar/find_mail_id.sql
pgpkg: 2024/10/11 16:59:14 parsing MOB dbstuff/bar/matching_mail.sql
pgpkg: 2024/10/11 16:59:14 select obj_type, obj_name from pgpkg.managed_object where pkg=$1 order by seq desc [foo]
pgpkg: 2024/10/11 16:59:14 savepoint statement
pgpkg: 2024/10/11 16:59:14 drop function if exists bar.matching_mail(name text)
pgpkg: 2024/10/11 16:59:14 release savepoint statement
pgpkg: 2024/10/11 16:59:14 savepoint statement
pgpkg: 2024/10/11 16:59:14 drop trigger if exists insert_mail_id_trigger on bar.FOO_Table
**pgpkg: 2024/10/11 16:59:14 [notice] relation "bar.foo_table" does not exist, skipping**
pgpkg: 2024/10/11 16:59:14 release savepoint statement
pgpkg: 2024/10/11 16:59:14 savepoint statement
pgpkg: 2024/10/11 16:59:14 drop function if exists bar.find_mail_id()
pgpkg: 2024/10/11 16:59:14 rollback to savepoint statement
pgpkg: 2024/10/11 16:59:14 savepoint statement
pgpkg: 2024/10/11 16:59:14 drop function if exists bar.find_mail_id()
pgpkg: 2024/10/11 16:59:14 rollback to savepoint statement
<internal>:1: unable to install MOB: <internal>:1: unable to execute statement: pq: cannot drop function bar.find_mail_id() because other objects depend on it
<internal>:1: unable to execute statement: pq: cannot drop function bar.find_mail_id() because other objects depend on it
pgpkg: 2024/10/11 16:59:14
pgpkg: 2024/10/11 16:59:14 -->    1: drop function if exists bar.find_mail_id()
```

As you can see, `bar."FOO_Table" is not adequately quoted, and therefore the drop fails.

A secondary issue is that the error is pretty confusing if I run this without `--verbose` (the "notice" line + the last 5 lines from above). The real error is marked as a notice, and the last lines are a red herring.

**Comment by doctor-eval** [comment]
I've just committed a fix for this. Unfortunately, if you have this problem, you will need to update pgpkg.managed_object to quote the schema name to fix it.

In terms of the error message, it's really an artefact of the bug, so this shouldn't be possible any more after my fix. pgpkg doesn't assume the database is in "perfect condition" - for example you might drop a function during development for some reason - and I don't think it's ideal for pgpkg to complain too much about that sort of thing.

Let me know how you get on, then I can close the issue.

**Comment by felixyz** [comment]
Worked great! (After updating my go version). Nothing is in production yet, so no problem there.

I had to truncate `pg.managed_object` and then delete the managed objects by hand. It occurs to me that this is something that might be necessary often enough (when one gets oneself into tricky situations) that maybe pgpkg should have a subcommand for it? (`clean-mobs` or something)

Many thanks for the quick fix!

(Also, for the record, I wouldn't choose to use uppercase chars in table names if it were up to me. But it's just as well that pgpkg can handle them!)

**Comment by doctor-eval** [comment]
Hi Felix

That's awesome.

I could have updated the database tables as part of the pgpkg upgrade, but I was worried about how much work it would be to test it properly, and since it's alpha and I guessed you weren't in production, I didn't think it was worth the effort.

Once I get feedback from you or anyone else about potentially using pgpkg in production, I'll start considering pgpkg "beta" level, and will start using branches and releases. At that point I would definitely have cleaned up the managed_objects table to fix this bug.

Cheers
Mark
